// <auto-generated />
namespace PizzaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_ingredients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ingredients));
        
        string IMigrationMetadata.Id
        {
            get { return "201512192018207_add_ingredients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
