// <auto-generated />
namespace PizzaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_sample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_sample));
        
        string IMigrationMetadata.Id
        {
            get { return "201512191935490_delete_sample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
