// <auto-generated />
namespace PizzaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pizzaingredientmanytomanyaddedjoinedtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pizzaingredientmanytomanyaddedjoinedtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201601091421081_pizza ingredient many-to-many added joined table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
