// <auto-generated />
namespace PizzaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmanytomanypizzasandingredients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmanytomanypizzasandingredients));
        
        string IMigrationMetadata.Id
        {
            get { return "201601091243596_added many-to-many pizzas and ingredients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
